[package]
name = "watchcat"
version = "0.3.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
crossbeam-channel = "0.5.15"
magnus = "0.8"
notify = { version = "8.2.0", features = ["crossbeam-channel"] }
rb-sys = "0.9.119"
